# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 16:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0006_auto_20180113_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_when_joining', models.BooleanField(default=True, verbose_name='Add new members automatically')),
                ('remove_when_leaving', models.BooleanField(default=True, verbose_name='Remove leaving members automatically')),
            ],
        ),
        migrations.CreateModel(
            name='MailingListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='byro_mailman.MailingList')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailinglists', to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MailmanConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, help_text='e.g. https://foo.bar.de/api', max_length=300, null=True, verbose_name='Mailman API URL')),
                ('user', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mailman API Username')),
                ('password', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mailman API Password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
