# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 21:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byro_mailman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglistentry',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='mailinglistentry',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailinglists', to='members.Member'),
        ),
    ]
